version: "3"

services:
  webapp:
    build:
      context: .
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/home/node/app/docker-cms-bundle
      - node_modules:/home/node/app/docker-cms-bundle/node_modules
      - node_modules_keystone:/home/node/app/docker-cms-bundle/apps/keystone/node_modules
      - keystone_db:/home/node/app/docker-cms-bundle/apps/keystone/db
      - keystone_files:/public/keystone
    working_dir: /home/node/app/docker-cms-bundle/

volumes:
  node_modules:
  node_modules_keystone:
  keystone_db:
  keystone_files:
