version: "3"

services:
  webapp:
    build:
      context: .
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/home/node/app/docker-cms-bundle
      - node_modules:/home/node/app/docker-cms-bundle/node_modules
      - node_modules_keystone:/home/node/app/docker-cms-bundle/apps/keystone/node_modules
      - keystone_files:/public/keystone
    working_dir: /home/node/app/docker-cms-bundle/
    depends_on:
      - keystone_postgres_db

  keystone_postgres_db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - keystone_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret_secret_secret
      - POSTGRES_USER=pguser
      - POSTGRES_DB=pgdb

volumes:
  node_modules:
  node_modules_keystone:
  keystone_files:
  keystone_postgres: {}
