version: "3"

services:
  payload:
    image: node:20-alpine
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - node_modules_payload:/home/node/app/app/payload/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev -w payload && npm run dev -w svelte"
    depends_on:
      - mongo
    env_file:
      - app/payload/.env
    environment:
      DATABASE_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
  node_modules_payload:
